product = "Angry Birds"
publisher = "Rovio"
name = "Angry Birds"
width = 1024
height = 600
orientation = 0
datapath = "data"
imagePath = "images/pc_build"
fontPath = "fonts/pc_build"
audioPath = "audio"
localizationPath = "localization"
levelPath = "levels"
scriptPath = "scripts"
deviceModel = "windows"
fullscreen = true
showCursor = false
