settings = {
	flurryFirstTimeLevelCollected = true,
	gameRestarted = 0,
	birdsShooted = 0,
	lastOpenLevel = 200,
	lastOpenLevelLP2 = 200,
	lastOpenLevelLP3 = 200,
	lastOpenLevelLP4 = 200,
	lastOpenLevelLP5 = 200,
	currentZoomLevelMainMenu = 1.83,
	wilhelmTell = false,
	bullsEye = false,
	cumulativeStars = 0,
	audioEnabled = true,
	gameCompleted = true,
	gameStarts = 122,
	totalLevelsCompleted = 0,
	currentLevelSelectionPages = {
	    goldeneggs = 1,
	    pack4 = 1,
	    pack5 = 1,
	    basic = 1,
	    pack6 = 1,
	    extra = 1,
	    pack3 = 1,
	},
	tutorials = {
	},
	gfxLowQuality = false,
	selectedEpisode = 1,
	lastOpenLevelLP6 = 200,
	cumulativeScore = "0",
	openGoldenEggLevels = {
	    Level5 = 0,
	},
	currentMainMenuTheme = "theme1",
	eaglesUsedIn = {
	},
}