introAnimation = {
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_1"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_2"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_1"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_2"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_1"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_2"}},

	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_1", "BIRD_FLYING_1"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_2", "BIRD_FLYING_2"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_1", "BIRD_FLYING_3"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_2", "BIRD_FLYING_4"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_1", "BIRD_FLYING_5"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SLEEP_2", "BIRD_FLYING_6"}},

	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_OK", "BIRD_NORMAL_1"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZE_1", "BIRD_NORMAL_1"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZE_2", "BIRD_FLIP_1"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZE_2", "BIRD_FLIP_2"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZED_1", "BIRD_FLIP_3"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZED_1", "BIRD_FLIP_4"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZED_1", "BIRD_FLIP_5"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZED_1", "BIRD_GROUND"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZED_1", "BIRD_GROUND", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_1", "PIGLETTE_SNEEZED_1", "BIRD_NORMAL_2"}},

	{time = 0.33, sprites = { "BEGINNING_BG_2", "PIGLETTE_SNEEZED_2", "BIRD_NORMAL_3"}},
	{time = 0.33, sprites = { "BEGINNING_BG_3", "BIRD_NORMAL_4", "CUTSCENE_YELLOW_BIRD_2"}},

	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_1"}},

	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_GROUND_TALK", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_1"}, "SWEARING"},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_GROUND_TALK", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},

	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_TALK", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_TALK", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_TALK", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_TALK", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_TALK", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_TALK", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_TALK", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_TALK", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_TALK", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_TALK", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_TALK", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_TALK", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_TALK", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_TALK", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_TALK", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_TALK", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_TALK", "CUTSCENE_BLACK_BIRD_1", "CUTSCENE_RED_BIRD_TALK", "CUTSCENE_GREEN_BIRD_1", "SWEARING"}},
	{time = 0.33, sprites = { "BEGINNING_BG_4", "BIRD_NORMAL_5", "CUTSCENE_YELLOW_BIRD_1", "CUTSCENE_BLACK_BIRD_TALK", "CUTSCENE_RED_BIRD_1", "CUTSCENE_GREEN_BIRD_TALK", "SWEARING"}},
}

birdAnimations = {
	blueBird = {
		time = 0.5,
		delayToNextAnimation = 4,
		frames = {},
	},
}--
filename="animations.lua"
