assetLoadList = {
	["1024x768"] = {
		["CUTSCENES_COMPOSPRITES"] = {
			"CUTSCENES_COMPOSPRITES.dat",
		},
		["THEME_06_COMPOSPRITES"] = {
			"THEME_06_COMPOSPRITES.dat",
		},
		["THEME_01"] = {
			"THEME_01_PARALLAX_1.dat",
			"THEME_01_THEME_GROUND_1.dat",
		},
		["THEME_02_COMPOSPRITES"] = {
			"THEME_02_COMPOSPRITES.dat",
		},
		["THEME_05"] = {
			"THEME_05_PARALLAX_5.dat",
			"THEME_05_THEME_GROUND_5.dat",
		},
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["THEME_10"] = {
			"THEME_10_PARALLAX_CAVE.dat",
			"THEME_10_THEME_GROUND_CAVE.dat",
		},
		["THEME_05_COMPOSPRITES"] = {
			"THEME_05_COMPOSPRITES.dat",
		},
		["THEME_09"] = {
			"THEME_09_PARALLAX_9.dat",
			"THEME_09_THEME_GROUND_9.dat",
		},
		["THEME_09_COMPOSPRITES"] = {
			"THEME_09_COMPOSPRITES.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_BACKGROUNDS_5.dat",
			"CUTSCENES_BACKGROUNDS_6.dat",
			"CUTSCENES_ELEMENTS_1.dat",
			"CUTSCENES_ELEMENTS_2.dat",
		},
		["THEME_04_COMPOSPRITES"] = {
			"THEME_04_COMPOSPRITES.dat",
		},
		["ACHIEVEMENTS"] = {
			"ACHIEVEMENTS_SHEET_1.dat",
		},
		["THEME_04"] = {
			"THEME_04_PARALLAX_4.dat",
			"THEME_04_THEME_GROUND_4.dat",
		},
		["THEME_07"] = {
			"THEME_07_PARALLAX_7.dat",
			"THEME_07_THEME_GROUND_7.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_BLOCKS_2.dat",
			"INGAME_COMPOSPRITES.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_PARALLAX_CRANES.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
			"INGAME_SKIES_3.dat",
		},
		["THEME_07_COMPOSPRITES"] = {
			"THEME_07_COMPOSPRITES.dat",
		},
		["THEME_06"] = {
			"THEME_06_PARALLAX_6.dat",
			"THEME_06_THEME_GROUND_6.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
			"SPLASHES_SHEET_3.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
		["THEME_08_COMPOSPRITES"] = {
			"THEME_08_COMPOSPRITES.dat",
		},
		["ROVIO_NEWS_COMPOSPRITES"] = {
			"ROVIO_NEWS_COMPOSPRITES.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"LEVELSELECTION_SHEET_2.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_MIGHTY_EAGLE_1.dat",
			"ROVIO_NEWS_SHEET_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["THEME_03_COMPOSPRITES"] = {
			"THEME_03_COMPOSPRITES.dat",
		},
		["THEME_03"] = {
			"THEME_03_PARALLAX_3.dat",
			"THEME_03_THEME_GROUND_3.dat",
		},
		["THEME_08"] = {
			"THEME_08_PARALLAX_8.dat",
			"THEME_08_THEME_GROUND_8.dat",
		},
		["THEME_01_COMPOSPRITES"] = {
			"THEME_01_COMPOSPRITES.dat",
		},
		["THEME_02"] = {
			"THEME_02_PARALLAX_2.dat",
			"THEME_02_THEME_GROUND_2.dat",
		},
	},

	["1024x768_lite"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_ELEMENTS_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["1024x768_palmhd"] = {
		["CUTSCENES_COMPOSPRITES"] = {
			"CUTSCENES_COMPOSPRITES.dat",
		},
		["THEME_06_COMPOSPRITES"] = {
			"THEME_06_COMPOSPRITES.dat",
		},
		["THEME_01"] = {
			"THEME_01_PARALLAX_1.dat",
			"THEME_01_THEME_GROUND_1.dat",
		},
		["THEME_02_COMPOSPRITES"] = {
			"THEME_02_COMPOSPRITES.dat",
		},
		["THEME_05"] = {
			"THEME_05_PARALLAX_5.dat",
			"THEME_05_THEME_GROUND_5.dat",
		},
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["THEME_10"] = {
			"THEME_10_PARALLAX_CAVE.dat",
			"THEME_10_THEME_GROUND_CAVE.dat",
		},
		["THEME_05_COMPOSPRITES"] = {
			"THEME_05_COMPOSPRITES.dat",
		},
		["THEME_09"] = {
			"THEME_09_PARALLAX_9.dat",
			"THEME_09_THEME_GROUND_9.dat",
		},
		["THEME_09_COMPOSPRITES"] = {
			"THEME_09_COMPOSPRITES.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_BACKGROUNDS_5.dat",
			"CUTSCENES_BACKGROUNDS_6.dat",
			"CUTSCENES_ELEMENTS_1.dat",
			"CUTSCENES_ELEMENTS_2.dat",
		},
		["THEME_04_COMPOSPRITES"] = {
			"THEME_04_COMPOSPRITES.dat",
		},
		["ACHIEVEMENTS"] = {
			"ACHIEVEMENTS_SHEET_1.dat",
		},
		["THEME_04"] = {
			"THEME_04_PARALLAX_4.dat",
			"THEME_04_THEME_GROUND_4.dat",
		},
		["THEME_07"] = {
			"THEME_07_PARALLAX_7.dat",
			"THEME_07_THEME_GROUND_7.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_BLOCKS_2.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_PARALLAX_CRANES.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
			"INGAME_SKIES_3.dat",
		},
		["THEME_07_COMPOSPRITES"] = {
			"THEME_07_COMPOSPRITES.dat",
		},
		["THEME_06"] = {
			"THEME_06_PARALLAX_6.dat",
			"THEME_06_THEME_GROUND_6.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
			"SPLASHES_SHEET_3.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
		["THEME_08_COMPOSPRITES"] = {
			"THEME_08_COMPOSPRITES.dat",
		},
		["ROVIO_NEWS_COMPOSPRITES"] = {
			"ROVIO_NEWS_COMPOSPRITES.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"LEVELSELECTION_SHEET_2.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_MIGHTY_EAGLE_1.dat",
			"ROVIO_NEWS_SHEET_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["THEME_03_COMPOSPRITES"] = {
			"THEME_03_COMPOSPRITES.dat",
		},
		["THEME_03"] = {
			"THEME_03_PARALLAX_3.dat",
			"THEME_03_THEME_GROUND_3.dat",
		},
		["THEME_08"] = {
			"THEME_08_PARALLAX_8.dat",
			"THEME_08_THEME_GROUND_8.dat",
		},
		["THEME_01_COMPOSPRITES"] = {
			"THEME_01_COMPOSPRITES.dat",
		},
		["THEME_02"] = {
			"THEME_02_PARALLAX_2.dat",
			"THEME_02_THEME_GROUND_2.dat",
		},
	},

	["1280x800"] = {
		["CUTSCENES_COMPOSPRITES"] = {
			"CUTSCENES_COMPOSPRITES.dat",
		},
		["THEME_06_COMPOSPRITES"] = {
			"THEME_06_COMPOSPRITES.dat",
		},
		["THEME_01"] = {
			"THEME_01_PARALLAX_1.dat",
			"THEME_01_THEME_GROUND_1.dat",
		},
		["THEME_02_COMPOSPRITES"] = {
			"THEME_02_COMPOSPRITES.dat",
		},
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["THEME_05_COMPOSPRITES"] = {
			"THEME_05_COMPOSPRITES.dat",
		},
		["THEME_07"] = {
			"THEME_07_PARALLAX_7.dat",
			"THEME_07_THEME_GROUND_7.dat",
		},
		["THEME_10"] = {
			"THEME_10_PARALLAX_CAVE.dat",
			"THEME_10_THEME_GROUND_CAVE.dat",
		},
		["THEME_09"] = {
			"THEME_09_PARALLAX_9.dat",
			"THEME_09_THEME_GROUND_9.dat",
		},
		["THEME_04_COMPOSPRITES"] = {
			"THEME_04_COMPOSPRITES.dat",
		},
		["THEME_07_COMPOSPRITES"] = {
			"THEME_07_COMPOSPRITES.dat",
		},
		["THEME_09_COMPOSPRITES"] = {
			"THEME_09_COMPOSPRITES.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_BLOCKS_2.dat",
			"INGAME_COMPOSPRITES.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_PARALLAX_CRANES.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
			"INGAME_SKIES_3.dat",
		},
		["THEME_05"] = {
			"THEME_05_PARALLAX_5.dat",
			"THEME_05_THEME_GROUND_5.dat",
		},
		["THEME_06"] = {
			"THEME_06_PARALLAX_6.dat",
			"THEME_06_THEME_GROUND_6.dat",
		},
		["THEME_03_COMPOSPRITES"] = {
			"THEME_03_COMPOSPRITES.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
		["THEME_08_COMPOSPRITES"] = {
			"THEME_08_COMPOSPRITES.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_BACKGROUNDS_5.dat",
			"CUTSCENES_ELEMENTS_1.dat",
			"CUTSCENES_ELEMENTS_2.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"LEVELSELECTION_SHEET_2.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["THEME_04"] = {
			"THEME_04_PARALLAX_4.dat",
			"THEME_04_THEME_GROUND_4.dat",
		},
		["THEME_03"] = {
			"THEME_03_PARALLAX_3.dat",
			"THEME_03_THEME_GROUND_3.dat",
		},
		["THEME_08"] = {
			"THEME_08_PARALLAX_8.dat",
			"THEME_08_THEME_GROUND_8.dat",
		},
		["THEME_01_COMPOSPRITES"] = {
			"THEME_01_COMPOSPRITES.dat",
		},
		["THEME_02"] = {
			"THEME_02_PARALLAX_2.dat",
			"THEME_02_THEME_GROUND_2.dat",
		},
	},

	["1280x800_lite"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_ELEMENTS_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["320x240_android_partial"] = {
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_2.dat",
			"GOLDEN_EGGS_SHEET_3.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"LEVELSELECTION_SHEET_2.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_ELEMENTS_3.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["400x320_lite"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"BACKGROUNDS_UPSELL_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_LITE_1.dat",
			"BUTTONS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_LITE_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["400x320_palm_partial"] = {
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_2.dat",
			"GOLDEN_EGGS_SHEET_3.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["480x320"] = {
		["CUTSCENES_COMPOSPRITES"] = {
			"CUTSCENES_COMPOSPRITES.dat",
		},
		["THEME_06_COMPOSPRITES"] = {
			"THEME_06_COMPOSPRITES.dat",
		},
		["THEME_01"] = {
			"THEME_01_PARALLAX_1.dat",
			"THEME_01_THEME_GROUND_1.dat",
		},
		["THEME_02_COMPOSPRITES"] = {
			"THEME_02_COMPOSPRITES.dat",
		},
		["THEME_05"] = {
			"THEME_05_PARALLAX_5.dat",
			"THEME_05_THEME_GROUND_5.dat",
		},
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["THEME_10"] = {
			"THEME_10_PARALLAX_CAVE.dat",
			"THEME_10_THEME_GROUND_CAVE.dat",
		},
		["THEME_05_COMPOSPRITES"] = {
			"THEME_05_COMPOSPRITES.dat",
		},
		["THEME_09"] = {
			"THEME_09_PARALLAX_9.dat",
			"THEME_09_THEME_GROUND_9.dat",
		},
		["THEME_09_COMPOSPRITES"] = {
			"THEME_09_COMPOSPRITES.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["THEME_04_COMPOSPRITES"] = {
			"THEME_04_COMPOSPRITES.dat",
		},
		["ACHIEVEMENTS"] = {
			"ACHIEVEMENTS_SHEET_1.dat",
		},
		["THEME_04"] = {
			"THEME_04_PARALLAX_4.dat",
			"THEME_04_THEME_GROUND_4.dat",
		},
		["THEME_07"] = {
			"THEME_07_PARALLAX_7.dat",
			"THEME_07_THEME_GROUND_7.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_BLOCKS_2.dat",
			"INGAME_COMPOSPRITES.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_PARALLAX_CRANES.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
			"INGAME_SKIES_3.dat",
		},
		["THEME_07_COMPOSPRITES"] = {
			"THEME_07_COMPOSPRITES.dat",
		},
		["THEME_06"] = {
			"THEME_06_PARALLAX_6.dat",
			"THEME_06_THEME_GROUND_6.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
		["THEME_08_COMPOSPRITES"] = {
			"THEME_08_COMPOSPRITES.dat",
		},
		["ROVIO_NEWS_COMPOSPRITES"] = {
			"ROVIO_NEWS_COMPOSPRITES.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_2.dat",
			"GOLDEN_EGGS_SHEET_3.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_ELEMENTS_3.dat",
			"MENU_GAMECENTER_1.dat",
			"MENU_MIGHTY_EAGLE_1.dat",
			"ROVIO_NEWS_SHEET_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["THEME_03_COMPOSPRITES"] = {
			"THEME_03_COMPOSPRITES.dat",
		},
		["THEME_03"] = {
			"THEME_03_PARALLAX_3.dat",
			"THEME_03_THEME_GROUND_3.dat",
		},
		["THEME_08"] = {
			"THEME_08_PARALLAX_8.dat",
			"THEME_08_THEME_GROUND_8.dat",
		},
		["THEME_01_COMPOSPRITES"] = {
			"THEME_01_COMPOSPRITES.dat",
		},
		["THEME_02"] = {
			"THEME_02_PARALLAX_2.dat",
			"THEME_02_THEME_GROUND_2.dat",
		},
	},

	["480x320_android_partial"] = {
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_2.dat",
			"GOLDEN_EGGS_SHEET_3.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_ELEMENTS_3.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["480x320_lite"] = {
		["ACHIEVEMENTS"] = {
			"ACHIEVEMENTS_SHEET_1.dat",
		},
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"BACKGROUNDS_UPSELL_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_GAMECENTER_1.dat",
			"BUTTONS_LITE_1.dat",
			"BUTTONS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_GAMECENTER_1.dat",
			"MENU_LITE_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["480x320_lite_palm"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"BACKGROUNDS_UPSELL_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_LITE_1.dat",
			"BUTTONS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_LITE_1.dat",
			"TUTORIALS_composprites.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
		},
	},

	["640x360"] = {
		["CUTSCENES_COMPOSPRITES"] = {
			"CUTSCENES_COMPOSPRITES.dat",
		},
		["THEME_06_COMPOSPRITES"] = {
			"THEME_06_COMPOSPRITES.dat",
		},
		["THEME_01"] = {
			"THEME_01_PARALLAX_1.dat",
			"THEME_01_THEME_GROUND_1.dat",
		},
		["THEME_02_COMPOSPRITES"] = {
			"THEME_02_COMPOSPRITES.dat",
		},
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["THEME_05_COMPOSPRITES"] = {
			"THEME_05_COMPOSPRITES.dat",
		},
		["THEME_07"] = {
			"THEME_07_PARALLAX_7.dat",
			"THEME_07_THEME_GROUND_7.dat",
		},
		["THEME_10"] = {
			"THEME_10_PARALLAX_CAVE.dat",
			"THEME_10_THEME_GROUND_CAVE.dat",
		},
		["THEME_09"] = {
			"THEME_09_PARALLAX_9.dat",
			"THEME_09_THEME_GROUND_9.dat",
		},
		["THEME_04_COMPOSPRITES"] = {
			"THEME_04_COMPOSPRITES.dat",
		},
		["THEME_07_COMPOSPRITES"] = {
			"THEME_07_COMPOSPRITES.dat",
		},
		["THEME_09_COMPOSPRITES"] = {
			"THEME_09_COMPOSPRITES.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_BLOCKS_2.dat",
			"INGAME_COMPOSPRITES.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_PARALLAX_CRANES.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
			"INGAME_SKIES_3.dat",
		},
		["THEME_05"] = {
			"THEME_05_PARALLAX_5.dat",
			"THEME_05_THEME_GROUND_5.dat",
		},
		["THEME_06"] = {
			"THEME_06_PARALLAX_6.dat",
			"THEME_06_THEME_GROUND_6.dat",
		},
		["THEME_03_COMPOSPRITES"] = {
			"THEME_03_COMPOSPRITES.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
		["THEME_08_COMPOSPRITES"] = {
			"THEME_08_COMPOSPRITES.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_2.dat",
			"GOLDEN_EGGS_SHEET_3.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_ELEMENTS_3.dat",
			"MENU_SHEET_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["THEME_04"] = {
			"THEME_04_PARALLAX_4.dat",
			"THEME_04_THEME_GROUND_4.dat",
		},
		["THEME_03"] = {
			"THEME_03_PARALLAX_3.dat",
			"THEME_03_THEME_GROUND_3.dat",
		},
		["THEME_08"] = {
			"THEME_08_PARALLAX_8.dat",
			"THEME_08_THEME_GROUND_8.dat",
		},
		["THEME_01_COMPOSPRITES"] = {
			"THEME_01_COMPOSPRITES.dat",
		},
		["THEME_02"] = {
			"THEME_02_PARALLAX_2.dat",
			"THEME_02_THEME_GROUND_2.dat",
		},
	},

	["640x360_china"] = {
		["CHINA"] = {
			"MISC_SHEET_1.dat",
		},
	},

	["640x360_korea"] = {
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
		},
	},

	["640x360_lite"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"BACKGROUNDS_UPSELL_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_LITE_1.dat",
			"BUTTONS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["864x480"] = {
		["CUTSCENES_COMPOSPRITES"] = {
			"CUTSCENES_COMPOSPRITES.dat",
		},
		["THEME_06_COMPOSPRITES"] = {
			"THEME_06_COMPOSPRITES.dat",
		},
		["THEME_01"] = {
			"THEME_01_PARALLAX_1.dat",
			"THEME_01_THEME_GROUND_1.dat",
		},
		["THEME_02_COMPOSPRITES"] = {
			"THEME_02_COMPOSPRITES.dat",
		},
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["THEME_05_COMPOSPRITES"] = {
			"THEME_05_COMPOSPRITES.dat",
		},
		["THEME_07"] = {
			"THEME_07_PARALLAX_7.dat",
			"THEME_07_THEME_GROUND_7.dat",
		},
		["THEME_10"] = {
			"THEME_10_PARALLAX_CAVE.dat",
			"THEME_10_THEME_GROUND_CAVE.dat",
		},
		["THEME_09"] = {
			"THEME_09_PARALLAX_9.dat",
			"THEME_09_THEME_GROUND_9.dat",
		},
		["THEME_04_COMPOSPRITES"] = {
			"THEME_04_COMPOSPRITES.dat",
		},
		["THEME_07_COMPOSPRITES"] = {
			"THEME_07_COMPOSPRITES.dat",
		},
		["THEME_09_COMPOSPRITES"] = {
			"THEME_09_COMPOSPRITES.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
			"SPLASHES_SHEET_3.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_BLOCKS_2.dat",
			"INGAME_COMPOSPRITES.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_PARALLAX_CRANES.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
			"INGAME_SKIES_3.dat",
		},
		["THEME_05"] = {
			"THEME_05_PARALLAX_5.dat",
			"THEME_05_THEME_GROUND_5.dat",
		},
		["THEME_06"] = {
			"THEME_06_PARALLAX_6.dat",
			"THEME_06_THEME_GROUND_6.dat",
		},
		["THEME_03_COMPOSPRITES"] = {
			"THEME_03_COMPOSPRITES.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
		["THEME_08_COMPOSPRITES"] = {
			"THEME_08_COMPOSPRITES.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_BACKGROUNDS_5.dat",
			"CUTSCENES_BACKGROUNDS_6.dat",
			"CUTSCENES_ELEMENTS_1.dat",
			"CUTSCENES_ELEMENTS_2.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_2.dat",
			"GOLDEN_EGGS_SHEET_3.dat",
			"GOLDEN_EGGS_SHEET_4.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"LEVELSELECTION_SHEET_2.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_ELEMENTS_2.dat",
			"MENU_MIGHTY_EAGLE_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["THEME_04"] = {
			"THEME_04_PARALLAX_4.dat",
			"THEME_04_THEME_GROUND_4.dat",
		},
		["THEME_03"] = {
			"THEME_03_PARALLAX_3.dat",
			"THEME_03_THEME_GROUND_3.dat",
		},
		["THEME_08"] = {
			"THEME_08_PARALLAX_8.dat",
			"THEME_08_THEME_GROUND_8.dat",
		},
		["THEME_01_COMPOSPRITES"] = {
			"THEME_01_COMPOSPRITES.dat",
		},
		["THEME_02"] = {
			"THEME_02_PARALLAX_2.dat",
			"THEME_02_THEME_GROUND_2.dat",
		},
	},

	["864x480_lite"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
			"SPLASHES_SHEET_3.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["864x480_lite_beta"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"BACKGROUNDS_UPSELL_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_LITEBETA_1.dat",
			"BUTTONS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_BACKGROUNDS_1.dat",
			"MENU_ELEMENTS_1.dat",
			"MENU_LITEBETA_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
			"SPLASHES_SHEET_3.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_BACKGROUNDS_4.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["TUTORIALS_COMPOSPRITES"] = {
			"TUTORIALS_COMPOSPRITES.dat",
		},
	},

	["960x640"] = {
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_ELEMENTS_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_ELEMENTS_1.dat",
			"CUTSCENES_ELEMENTS_2.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
		},
	},

	["960x640_lite"] = {
		["OTHER"] = {
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"MENU_ELEMENTS_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_ELEMENTS_1.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
		},
	},

	["pc_build"] = {
		["OTHER"] = {
			"BACKGROUNDS_GE_1.dat",
			"BACKGROUNDS_LS_1.dat",
			"BACKGROUNDS_MAIN_1.dat",
			"POPUPS_SHEET_1.dat",
		},
		["MENU"] = {
			"BUTTONS_SHEET_1.dat",
			"GOLDEN_EGGS_SHEET_1.dat",
			"LEVELSELECTION_SHEET_1.dat",
			"LEVELSELECTION_SHEET_2.dat",
			"MENU_ELEMENTS_1.dat",
			"TUTORIALS_SHEET_1.dat",
		},
		["INGAME"] = {
			"INGAME_BIRDS_1.dat",
			"INGAME_BIRDS_2.dat",
			"INGAME_BLOCKS_1.dat",
			"INGAME_GROUNDS_1.dat",
			"INGAME_SKIES_1.dat",
			"INGAME_SKIES_2.dat",
		},
		["CUTSCENES"] = {
			"CUTSCENES_BACKGROUNDS_1.dat",
			"CUTSCENES_BACKGROUNDS_2.dat",
			"CUTSCENES_BACKGROUNDS_3.dat",
			"CUTSCENES_ELEMENTS_1.dat",
			"CUTSCENES_ELEMENTS_2.dat",
		},
		["SPLASHES"] = {
			"SPLASHES_SHEET_1.dat",
			"SPLASHES_SHEET_2.dat",
		},
	},

	["wp7"] = {
		["MENU"] = {
			"MENU_FULL_GAME_BUTTONS.dat",
			"MENU_SHEET_1.dat",
			"MENU_SHEET_2.dat",
			"MENU_SHEET_3.dat",
			"MENU_SHEET_4.dat",
			"MENU_SHEET_5.dat",
			"MENU_SHEET_6.dat",
		},
	},

}
--
filename="loadlist.lua"
