assetLoadList = {
	["1024x768_pc"] = {
	  CUTSCENES_COMPOSPRITES = {
		"CUTSCENES_composprites.dat"
	  },
	  THEME_2 = {
		"INGAME_PARALLAX_2.dat",
		"INGAME_THEME_GROUND_2.dat"
	  },
	  CUTSCENES = {
		"CUTSCENES_BACKGROUNDS_1.dat",
		"CUTSCENES_BACKGROUNDS_10.dat",
		"CUTSCENES_BACKGROUNDS_11.dat",
		"CUTSCENES_BACKGROUNDS_12.dat",
		"CUTSCENES_BACKGROUNDS_2.dat",
		"CUTSCENES_BACKGROUNDS_3.dat",
		"CUTSCENES_BACKGROUNDS_4.dat",
		"CUTSCENES_BACKGROUNDS_5.dat",
		"CUTSCENES_BACKGROUNDS_6.dat",
		"CUTSCENES_BACKGROUNDS_7.dat",
		"CUTSCENES_BACKGROUNDS_8.dat",
		"CUTSCENES_BACKGROUNDS_9.dat",
		"CUTSCENES_ELEMENTS_1.dat",
		"CUTSCENES_ELEMENTS_2.dat",
		"CUTSCENES_ELEMENTS_3.dat",
		"CUTSCENES_ELEMENTS_4.dat",
		"CUTSCENES_ELEMENTS_5.dat",
		"CUTSCENES_ELEMENTS_6.dat",
		"CUTSCENES_ELEMENTS_7.dat",
		"CUTSCENES_ELEMENTS_PC_CUTSCENES.dat"
	  },
	  GOLDEN_EGGS = {
		"BACKGROUNDS_GE_1.dat",
		"GOLDEN_EGGS_SHEET_1.dat",
		"GOLDEN_EGGS_SHEET_2.dat",
	  	"BIRDS_SHEET_1.dat"
	  },
	  LEVELSELECTION = {
		"BACKGROUNDS_LS_1.dat",
		"LEVELSELECTION_SHEET_1.dat",
		"LEVELSELECTION_SHEET_2.dat"
	  },
	  OTHER = {
		"BACKGROUNDS_MAIN_1.dat",
--		"BUTTONS_SHEET_3.dat",
		"BUTTONS_SHEET_1.dat",
		"BUTTONS_SHEET_2.dat",
		"HUD_INGAME_1.dat",
		"EPISODES_SHEET_1.dat",
		"CURSORS_SHEET_1.dat",
		"INGAME_PARALLAX_CRANES.dat",
		"POPUPS_SHEET_1.dat",
		"TUTORIALS_SHEET_1.dat"
	  },
	  THEME_7 = {
		"INGAME_PARALLAX_7.dat",
		"INGAME_THEME_GROUND_7.dat"
	  },
	  THEME_10 = {
		"INGAME_PARALLAX_10.dat",
		"INGAME_THEME_GROUND_10.dat"
	  },
	  THEME_5 = {
		"INGAME_PARALLAX_5.dat",
		"INGAME_THEME_GROUND_5.dat"
	  },
	  THEME_6 = {
		"INGAME_PARALLAX_6.dat",
		"INGAME_THEME_GROUND_6.dat"
	  },
	  THEME_8 = {
		"INGAME_PARALLAX_8.dat",
		"INGAME_THEME_GROUND_8.dat"
	  },
	  TUTORIALS_COMPOSPRITES = {
		"TUTORIALS_composprites.dat"
	  },
	  THEME_1 = {
		"INGAME_PARALLAX_1.dat",
		"INGAME_THEME_GROUND_1.dat"
	  },
	  OTHER_2 = {
		"MENU_ELEMENTS_1.dat",
		"MENU_ELEMENTS_2.dat", --MENU_L2GO
		"INGAME_SCORES_SHEET_1.dat"
	  },
	  SPLASHES = {
		"SPLASHES_SHEET_1.dat",
		"SPLASHES_SHEET_2.dat",
		"SPLASHES_SHEET_3.dat"
	  },
	  THEME_9 = {
		"INGAME_PARALLAX_9.dat",
		"INGAME_THEME_GROUND_9.dat"
	  },
	  THEME_4 = {
		"INGAME_PARALLAX_4.dat",
		"INGAME_THEME_GROUND_4.dat"
	  },
	  THEME_3 = {
		"INGAME_PARALLAX_3.dat",
		"INGAME_THEME_GROUND_3.dat"
	  },
	  INGAME = {
		"INGAME_BIRDS_1.dat",
		"INGAME_BIRDS_2.dat",
		"INGAME_BLOCKS_1.dat",
		"INGAME_BLOCKS_2.dat",
		"INGAME_BLOCKS_3.dat",
		"INGAME_BLOCKS_4.dat",
		"INGAME_GROUNDS_1.dat",
		"INGAME_SKIES_1.dat",
		"INGAME_SKIES_2.dat",
		"INGAME_SKIES_3.dat"
	  },
	}
}
--
filename = "loadlist.lua"
